&Aerosol_Detect_Coeffs
N__Num_Aerosol_Tests = 3
N__Num_Aerosol_Chans(1:3) = 4, 4, 4
N__Aerosol_Chans(1,1:4) = 1340, 2348, 1782, 2356
N__Aerosol_Chans(2,1:4) = 2093, 2348, 1782, 2356
N__Aerosol_Chans(3,1:4) = 1782, 2356, 1782,  753
N__Mean_Aerosol_Chans = 11
R__Aerosol_TBD(1,1:2) = 0.2, -1.55
R__Aerosol_TBD(2,1:2) = -1.5, 999.9
R__Aerosol_TBD(3,1:2) = -1.8, -2.0
R__Rank_Thres_Coeff(1:3) = -0.01, 2.1, -3.9
R__Unclassified_Thres = 0.4
R__Land_Fraction_Thres = 0.5
/
