&Aerosol_Detect_Coeffs
N__Num_Aerosol_Tests = 3
N__Num_Aerosol_Chans(1:3) = 4, 4, 4
N__Aerosol_Chans(1,1:4) = 2679, 4695, 3563, 4711
N__Aerosol_Chans(2,1:4) = 4185, 4695, 3563, 4711
N__Aerosol_Chans(3,1:4) = 3563, 4711, 3563, 1505
N__Mean_Aerosol_Chans = 21
R__Aerosol_TBD(1,1:2) = -999.9, -999.9
R__Aerosol_TBD(2,1:2) = -999.9, -999.9
R__Aerosol_TBD(3,1:2) = -999.9, -999.9
R__Rank_Thres_Coeff(1:3) = -0.01, 2.1, -3.9
R__Unclassified_Thres = 0.4
R__Land_Fraction_Thres = 0.5
/
